name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          npx expo prebuild --platform android
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk
          path: .
      
      - name: Changing timezone for tag name
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Singapore"

      - name: Create Tag Name
        id: create_tag
        run: |
          TAG_NAME="release-$(date +'%Y%m%d%H%M%S')"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
    
      - name: Print Tag Name
        run: echo "TAG_NAME=${{ steps.create_tag.outputs.tag_name }}"
  
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            files: ./app-release.apk
            tag_name: ${{ steps.create_tag.outputs.tag_name }}
            generate_release_notes: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
